### ISSUE TITLE
Is there an update for Mapbox v10?

### ISSUE THREAD

**Issue by AF-cgi** [GEOSwift/GEOSwiftMapboxGL#14]
Do you plan to migrate this repo to https://github.com/mapbox/mapbox-maps-ios? Or isn't it necessary anymore?

**Comment by macdrevx** [comment]
I think we should do something. Mapbox v10 has Turf as a dependency which offers similar features to GEOSwift, but I think there are likely still use cases that only GEOSwift supports.
