### ISSUE TITLE
Handle optional for Geometry.collection()

### ISSUE THREAD

**Issue by Hugal31** [GEOSwift/GEOSwiftMapboxGL#2]
The last version of GEOSwift made `Geometry.collection()` [returns an optional](https://github.com/GEOSwift/GEOSwift/commit/6006a7493dc040909903559d6b49cfe5d0070ecc).

This package doesn't compile anymore due to an error in [MapboxGLAnnotation, line 88](https://github.com/GEOSwift/GEOSwiftMapboxGL/blob/master/GEOSwiftMapboxGL/MapboxGLAnnotations.swift#L88):

```
MapboxGLAnnotations.swift:88:81: error: value of optional type 'Waypoint?' not unwrapped; did you mean to use '!' or '?'?
        self.centroid = CLLocationCoordinate2DFromCoordinate(geometryCollection.centroid().coordinate)
```

Tell me if I am wrong but I think we can solve the problem by simply adding `!` after the call to `centroid`.

**Comment by vfn** [comment]
@Hugal31 that's correct, you can "fix it" by force-unwrapping the optional value , although that's not a good thing to do.

The proper fix would be to handle the optional value, by either having a workaround solution for the centroid, like making it an invalid coordinate or transforming that initializer into an failable one, and return nil if the centroid is nil:
```Swift
required public init<GEOSwiftMapboxGL>?(geometryCollection: GeometryCollection<GEOSwiftMapboxGL>) {
...
}
```

Would you be interested on creating a pull request to fix it?

**Comment by Hugal31** [comment]
Thank you for your reply.

I thought `centroid` would always return `Some` because all the handled
cases resolve to a `Waypoint` in the `centroid` function.

I will make a pull request soon.

**Comment by vfn** [comment]
@Hugal31 thank you for helping with https://github.com/GEOSwift/GEOSwiftMapboxGL/pull/3. I'm adding you as a member of the team.

Please let me know what email you'd like to use for interacting with Cocoapods and releasing pod versions
