### ISSUE TITLE
Hello, I want to convert WKT into Geojson

### ISSUE THREAD

**Issue by songyuyang0918** [GEOSwift/GEOSwiftMapboxGL#5]
Dear developers, I have been in touch with your framework for the first time and would like to know if there are any documents to read?
I want to convert WKT to Geojson.
Thank you very much.

**Comment by vfn** [comment]
The little documentation on the README file should help you get started https://github.com/GEOSwift/GEOSwiftMapboxGL/blob/master/README.md

You might also want to check the README on GEOSwift project for more info. https://github.com/GEOSwift/GEOSwift/blob/master/README.md
