### ISSUE TITLE
Pod Update updated to GEOSwift 2.2.0 and I get compile error.

### ISSUE THREAD

**Issue by nylemusgrave** [GEOSwift/GEOSwiftMapboxGL#6]
MapboxGLAnnotations.swift line 88

self.centroid = CLLocationCoordinate2DFromCoordinate(geometryCollection.centroid().coordinate)

Value of optional type 'Waypoint?' not unwrapped; did you mean to use '!' or '?'"?

**Comment by vfn** [comment]
@nylemusgrave the code on `develop` branch had a fix for it. I have updated the pod version to contain the changed.
