### ISSUE TITLE
Dependency pod versions

### ISSUE THREAD

**Issue by srgray** [GEOSwift/GEOSwiftMapboxGL#8]
I'm unable to install this pod due to issues with dependencies (GEOSwift/geos):

```[!] Error installing geos
[!] /usr/bin/svn export --non-interactive --trust-server-cert --force https://svn.osgeo.org/geos/tags/3.5.0 /var/folders/yr/5k0s_v256xzdffy2t36x836w0000gn/T/d20181009-11479-5zvs85

svn: E170013: Unable to connect to a repository at URL 'https://svn.osgeo.org/geos/tags/3.5.0'
svn: E175013: Access to '/geos/tags/3.5.0' forbidden
```

The solution mentioned here: https://github.com/GEOSwift/GEOSwift/issues/78 seems to be to update the versions of GEOSwift/geos pods.

**Comment by srgray** [comment]
A fix for this is in: https://github.com/GEOSwift/GEOSwiftMapboxGL/pull/9

**Comment by rajtharan-g** [comment]
Same issue here also.

**Comment by macdrevx** [comment]
Closing this in light of the upcoming changes in #11. If you still have issues after that version is released, please reopen this with additional data.
